name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DAY_OF_WEEK: Monday
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        for i in $(ls .); do echo $i; done
